### ISSUE TITLE
Junk files

### ISSUE THREAD

**Issue by edysegura** [LuizFelipePereira/DM107#1]
There is no need to commit node_modules because it is a third party dependencies defined at `package.json`. To bring the dependencies you just need to run `npm install` in your project root folder.

I'd like to suggest you to put this folder to `.gitignore`.

![image](https://cloud.githubusercontent.com/assets/5324414/10884614/16303dcc-8160-11e5-9052-40e98c8abb40.png)

**Comment by LuizFelipePereira** [comment]
Ok já foi corrigido, Obrigado.

**Comment by edysegura** [comment]
Você fez o pull? O diretório `node_modules` ainda está lá:

![image](https://cloud.githubusercontent.com/assets/5324414/11022751/3337197a-864e-11e5-876d-fecafcc696cb.png)

**Comment by LuizFelipePereira** [comment]
Realmente esqueçi de fazer o pull, agora já correto. Obrigado.
