### ISSUE TITLE
Error to create a new delivery

### ISSUE THREAD

**Issue by edysegura** [LuizFelipePereira/DM107#4]
It was not possible to create a new delivery:

![image](https://cloud.githubusercontent.com/assets/5324414/10896253/df357806-819f-11e5-9aff-5caceaa2ee2f.png)

![image](https://cloud.githubusercontent.com/assets/5324414/10896287/22a55caa-81a0-11e5-9a07-cd7796237825.png)

**Comment by LuizFelipePereira** [comment]
Edy tem que passar o idEntrega tambem com o JSON, não deixei ele como um incremento.

![sem titulo](https://cloud.githubusercontent.com/assets/12371505/10896619/4793bc58-81a2-11e5-99a4-9571613e5d59.png)

**Comment by edysegura** [comment]
Entendi, obrigado!
